### ISSUE TITLE
AppImage/Solus install option

### ISSUE THREAD

**Issue by DefEspurr** [Taiko2k/Tauon#452]
Or permission to rewrap the file.

**Comment by Taiko2k** [comment]
Flatpak is the supported installation method. I'm not interested in maintaining another packaging format.

Otherwise, you could try install manually or create your own build script.

**Comment by C0rn3j** [comment]
> permission to rewrap the file

Tauon is licensed as GPL v3+.

Solus is a Linux distribution, so you can either use the Flatpak, build it manually as per the wiki, or use the prebuilt CI images that #1354 makes feasible.

I also see no point in supporting AppImage, though you are free to package it as such yourself if you wish, there probably wouldn't be an issue accepting a PR for it as long as someone else is willing to maintain it.

**Comment by ivan-hc** [comment]
Hi, I'm the developer of a package manager called [AM](https://github.com/ivan-hc/AM), and I distribute both AppImages and other portable formats.

I also package various programs in AppImage format, so much so that I maintain over 90 of them in my repositories.

I'd like to distribute your portable app, regardless of whether it's an AppImage or a static binary.

But I just downloaded both the prerelease zip archive and the latest 7z archive. The zip archive contains an additional 7z archive.

I could also write a script that converts the program to an AppImage, on the base of [these scripts](https://github.com/ivan-hc/AM/tree/main/appimage-bulder-scripts/x86_64), it would be easy... but I'd like you to maintain only one compression format: Your way of distributing it is strange! A builder should add two more checks to see if what has been extracted from the archive is another archive or the program itself.

If you find maintaining an AppImage complicated, at least don't complicate things by creating "matryoshkas" of archives to extract and analyze. That doesn't help at all.

Only if you solve this, I'll provide you with a build script like I did with [Calibre](https://github.com/ivan-hc/Calibre-appimage), which even a 6-year-old could run to create an AppImage without libfuse2 and with integrated delta updates.

Let me know if you're interested.

Best regards.

**Comment by C0rn3j** [comment]
> The zip archive contains an additional 7z archive.

It does, [we use](https://github.com/Taiko2k/Tauon/blob/5e9d8031737e2b74c1930fad1743b2d162bf7bd6/.github/workflows/build_and_release.yaml#L105-L109) upload-artifact action which re-zips everything with no way to disable it - https://github.com/actions/upload-artifact/issues/367 + https://github.com/actions/upload-artifact/issues/426.

You're more than welcome to send a PR with better way which ends up with a single .7z file, probably by ditching upload-artifact for something else.

The regular releases do not do this, only the pre-release workflow does.

I would imagine you'd want to package the stable releases, not pre-releases.

**Comment by ivan-hc** [comment]
I'm not a big expert on workflows, but I can share the ones I use
```
name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 23 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: build
      if: always()
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        chmod a+x ./builder.sh
        ./builder.sh
        mkdir dist
        mv *AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        # Snapshot Release
        - name: get date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: create snapshot
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot ${{ env.SNAPSHOT_TAG}}"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false

        # Continuous release
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
```

I can explain, what it does, piece-by-piece.

The jobs are two: **build** and **release**.

You already use something similar to my "build" job, that ends with the step "**actions/upload-artifact@v4.4.0**".

You need the "release" part, and I use here two approachs: "continuous" and "snapshot"

## Continuous
This uses the old (but still useful) marvinpinto/action-automatic-releases@latest
```
        # Continuous release
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
```
I use this for continuous releases. Files picked (from the "dist" directory, see "Upload Artifact") are the ones with "AppImage" in the name.

## Snapshot
This uses softprops/action-gh-release@v2 and I set theoutput of the command `date` as a tag, but you can use whatever you want, manually
```
        # Snapshot Release
        - name: get date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: create snapshot
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot ${{ env.SNAPSHOT_TAG}}"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false
```
Like "contiuous", it picks the files with that keyword in the name from the "dist" directory.

-------------------------------------------------

## How to move your artifact to the "dist" directory
In "build", see this
```
    - name: build
      if: always()
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        chmod a+x ./builder.sh
        ./builder.sh
        mkdir dist
        mv *AppImage* dist/
```
in partucular
```
        chmod a+x ./builder.sh
        ./builder.sh
        mkdir dist
        mv *AppImage* dist/
```
Here a script "builder.sh" creates something (in my case, an AppImage), then `mkdir dist` to create the directory, then move all targeted files to it with `mv *some-keyword* dist/`

--------------------------------------------------

End of the lesson.

@C0rn3j if you have other questions, let me know.
